services:
  - type: web
    name: nek-scout
    runtime: node
    plan: free
    buildCommand: npm install && DATABASE_URL="file:./prisma/dev.db" npm run build && DATABASE_URL="file:./prisma/dev.db" npm run seed
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        value: file:./prisma/dev.db
